# Generated by Django 6.0.5 on 2026-05-08 22:48

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_perfilusuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=tienda.models.renombrar_imagen, validators=[tienda.models.validar_imagen], verbose_name='Imagen del Juego'),
        ),
    ]
